version: "3"
services:
  backend:
    image: motion-drf:latest
    # open port 8000 on the local machine side(left) and port 8000 on the container side(right)
    ports:
      - "8000:8000"
#    command: "python manage.py runserver 0:8000"
    command: "tail -f /dev/null"
    volumes:
      - ./backend:/backend
    env_file:
      - ./envs/dev.env
    depends_on:
      - database

  database:
   image: postgres:latest
   ports:
    - "5555:5432"
   env_file:
    - ./envs/dev.env
   volumes:
   - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: