name: backend
dependencies:
  - python=3.6
  - psycopg2=2.9.9
  - pip=21.2.2
  - pip:
    - Django==2.2.2
    - flake8==5.0.4
    - djangorestframework==3.9.4
    - markdown==3.1.1
    - django-filter==2.1.0
    - djangorestframework_simplejwt==4.3.0
    - coreapi==2.3.3
    - Pygments==2.4.2
    - gunicorn
    - Pillow==10.2.0
    - django-cors-headers
    - pywebcopy
    - beautifulsoup4==4.7.1
    - django-extensions==2.2.5
    - django-fullurl==1.0
